# Generated by Django 5.0.1 on 2024-03-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Customers'},
        ),
    ]
