# Generated by Django 5.0.1 on 2024-04-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mailing_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
