# Generated by Django 5.0.1 on 2024-02-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permitnumber', models.BigIntegerField(null=True)),
            ],
        ),
    ]
