# Generated by Django 5.0.1 on 2024-07-02 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_rename_work_area_address_work_area_num'),
        ('customer', '0004_alter_customer_mailing_state'),
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit911',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permittime', models.DateTimeField(auto_now_add=True)),
                ('permitdate', models.DateField()),
                ('permitnumber', models.BigIntegerField(null=True)),
                ('permaddymvdate', models.TextField(max_length=25)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
                ('permcompany', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='address.electricprovider')),
                ('permnewaddy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='address.address')),
            ],
        ),
        migrations.DeleteModel(
            name='Permit',
        ),
    ]
