# Generated by Django 5.0.1 on 2024-07-02 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_rename_work_area_address_work_area_num'),
        ('permits', '0002_permit911_delete_permit'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit911',
            name='permoldaddy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poldaddress', to='address.address'),
        ),
        migrations.AlterField(
            model_name='permit911',
            name='permnewaddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pnewaddress', to='address.address'),
        ),
    ]
