# Generated by Django 5.1.1 on 2024-10-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_permit911_permoldaddy_alter_permit911_permnewaddy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit911',
            name='permaddymvdate',
            field=models.DateField(max_length=25),
        ),
    ]
