# Generated by Django 5.1.1 on 2024-10-28 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_address_lr'),
        ('permits', '0004_alter_permit911_permaddymvdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit911',
            name='permoldaddy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poldaddress', to='address.address'),
        ),
    ]
