# Generated by Django 5.1.1 on 2024-10-28 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_address_lr'),
        ('permits', '0005_alter_permit911_permoldaddy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit911',
            name='permnewaddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pnewaddress', to='address.address'),
        ),
    ]
