# Generated by Django 5.1.1 on 2024-10-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_alter_permit911_permnewaddy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit911',
            name='permaddymvdate',
            field=models.DateField(blank=True, max_length=25, null=True),
        ),
    ]
