# Generated by Django 5.1.1 on 2024-11-06 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0007_alter_permit911_permaddymvdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit911',
            name='permnewaddy',
        ),
        migrations.RemoveField(
            model_name='permit911',
            name='permoldaddy',
        ),
    ]
