# Generated by Django 5.1.1 on 2024-11-13 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_address_lr'),
        ('permits', '0008_remove_permit911_permnewaddy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit911',
            name='permnewaddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pnewaddress', to='address.address'),
        ),
        migrations.AddField(
            model_name='permit911',
            name='permoldaddy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poldaddress', to='address.address'),
        ),
    ]
