# Generated by Django 5.0.1 on 2024-02-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='aptnum',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
