# Generated by Django 5.0.1 on 2024-02-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_options_alter_address_aptnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lot_num',
            field=models.CharField(blank=True, null=True),
        ),
    ]
