# Generated by Django 5.0.1 on 2024-03-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_workarea_alter_address_work_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='work_area',
            new_name='work_area_num',
        ),
    ]
