# Generated by Django 5.1.1 on 2024-10-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_rename_work_area_address_work_area_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lr',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='R', max_length=1),
        ),
    ]
